In [1]:
import torch
import numpy as np


In [2]:
batch_size = 4
same_patch = np.eye(2*batch_size, k=batch_size // 2) * 9 + \
                         np.eye(2*batch_size, k=-batch_size // 2) * 9
atten_weights = np.ones((2*batch_size, 2*batch_size)) + same_patch

In [3]:
same_patch

array([[0., 0., 9., 0., 0., 0., 0., 0.],
       [0., 0., 0., 9., 0., 0., 0., 0.],
       [9., 0., 0., 0., 9., 0., 0., 0.],
       [0., 9., 0., 0., 0., 9., 0., 0.],
       [0., 0., 9., 0., 0., 0., 9., 0.],
       [0., 0., 0., 9., 0., 0., 0., 9.],
       [0., 0., 0., 0., 9., 0., 0., 0.],
       [0., 0., 0., 0., 0., 9., 0., 0.]])

In [5]:
atten_weights

array([[ 1.,  1., 10.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 10.,  1.,  1.,  1.,  1.],
       [10.,  1.,  1.,  1., 10.,  1.,  1.,  1.],
       [ 1., 10.,  1.,  1.,  1., 10.,  1.,  1.],
       [ 1.,  1., 10.,  1.,  1.,  1., 10.,  1.],
       [ 1.,  1.,  1., 10.,  1.,  1.,  1., 10.],
       [ 1.,  1.,  1.,  1., 10.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 10.,  1.,  1.]])

In [10]:
logits = np.random.random((2*batch_size, 2*batch_size))
logits

array([[0.72059393, 0.63630435, 0.29528284, 0.33397035, 0.89765019,
        0.57262973, 0.16674755, 0.72979142],
       [0.13519261, 0.10331729, 0.73248625, 0.81708899, 0.29195978,
        0.77286876, 0.14010348, 0.86322906],
       [0.82662146, 0.75524945, 0.83480043, 0.06630097, 0.25309997,
        0.52916611, 0.40647612, 0.16653468],
       [0.88839816, 0.45599196, 0.81344132, 0.19776321, 0.10311203,
        0.60683949, 0.00672615, 0.13767313],
       [0.3511524 , 0.82977883, 0.7224404 , 0.78533663, 0.51036913,
        0.08117027, 0.12536662, 0.46714901],
       [0.15215179, 0.24802353, 0.17395678, 0.50049236, 0.62261752,
        0.05950679, 0.44736801, 0.66706058],
       [0.53718232, 0.7622692 , 0.64547339, 0.92079206, 0.90261221,
        0.83678503, 0.01804873, 0.72330886],
       [0.90697876, 0.77495881, 0.27737801, 0.54829986, 0.89977263,
        0.91878249, 0.97735399, 0.35814697]])

In [11]:
logits*atten_weights

array([[7.20593933e-01, 6.36304352e-01, 2.95282835e+00, 3.33970351e-01,
        8.97650186e-01, 5.72629731e-01, 1.66747547e-01, 7.29791420e-01],
       [1.35192611e-01, 1.03317290e-01, 7.32486246e-01, 8.17088986e+00,
        2.91959782e-01, 7.72868758e-01, 1.40103478e-01, 8.63229060e-01],
       [8.26621460e+00, 7.55249451e-01, 8.34800431e-01, 6.63009704e-02,
        2.53099968e+00, 5.29166110e-01, 4.06476120e-01, 1.66534678e-01],
       [8.88398156e-01, 4.55991960e+00, 8.13441322e-01, 1.97763214e-01,
        1.03112031e-01, 6.06839490e+00, 6.72614544e-03, 1.37673131e-01],
       [3.51152395e-01, 8.29778834e-01, 7.22440398e+00, 7.85336625e-01,
        5.10369132e-01, 8.11702728e-02, 1.25366615e+00, 4.67149010e-01],
       [1.52151794e-01, 2.48023534e-01, 1.73956779e-01, 5.00492363e+00,
        6.22617520e-01, 5.95067929e-02, 4.47368010e-01, 6.67060584e+00],
       [5.37182321e-01, 7.62269196e-01, 6.45473393e-01, 9.20792059e-01,
        9.02612206e+00, 8.36785026e-01, 1.80487334e-02, 7.